name: MacOS application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app

jobs:
  NeedleFoundationTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleFoundationTests"
        run: xcodebuild test -project NeedleFoundation.xcodeproj -scheme NeedleFoundation -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
  NeedleGeneratorTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleGeneratorTests"
        run: cd Generator && swift test -Xswiftc -DDEBUG
  NeedleGeneratorBinary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleGeneratorBinary"
        run: cd Generator && swift build -c release
  NeedleSampleMVCApp:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleSampleMVCApp"
        run: xcodebuild build -project Sample/MVC/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToe -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
  NeedleSampleMVCTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleSampleMVCTests"
        run: xcodebuild test -project Sample/MVC/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToeTests -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
  NeedleSamplePluginizedApp:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleSamplePluginizedApp"
        run: xcodebuild build -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToe -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
  NeedleSamplePluginizedScoreSheetTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleSamplePluginizedScoreSheetTests"
        run: xcodebuild test -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme ScoreSheetTests -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
  NeedleSamplePluginizedTicTacToeCoreTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "NeedleSamplePluginizedTicTacToeCoreTests"
        run: xcodebuild test -project Sample/Pluginized/TicTacToe/TicTacToe.xcodeproj -scheme TicTacToeCoreTests -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
